site_name: UFBA Python Workshop
pages:
  - Home: index.md
  - Programa: program.md
  - Antes do Curso: setup.md
  - Links/Downloads: resources.md

theme_dir: mkdocs

site_description: Introdução à linguagem de programação Python
site_url: https://ocefpaf.github.io/python4oceanographers_intro_course
repo_url: https://github.com/ocefpaf/python4oceanographers_intro_course
site_author: Filipe Fernandes
site_favicon: favicon.png
docs_dir: src
site_dir: _site
copyright: <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US"><img alt="Creative Commons License" style="border-width:0" src="http://i.creativecommons.org/l/by-nc-sa/3.0/88x31.png" /></a><br /> <span xmlns:dct="http://purl.org/dc/terms/" href="http://purl.org/dc/dcmitype/Dataset" property="dct:title" rel="dct:type"> "UFBA Python Workshop"</span> by <a xmlns:cc="http://creativecommons.org/ns#" href="http://ocefpaf.github.io/" property="cc:attributionName" rel="cc:attributionURL">Filipe Fernandes</a> is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/3.0/deed.en_US"> Creative Commons Attribution-NonCommercial-ShareAlike 3.0 Unported License</a>.<br />
markdown_extensions:
    - toc:
        permalink: "<U+F0C1>"
    - extra
    - smarty
    - math
    - markdown_checklist.extension
extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','js/mathjaxhelper.js']
google_analytics: ['UA-9133259-16', 'ocefpaf.github.io']
